server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

url-shortener:
  default-expiration-minutes: 5
  base-url: http://localhost:8080
  short-code-length: 6

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket-name: ${MINIO_BUCKET_NAME}

# Scheduled Jobs
report:
  scheduler:
    cron: "0 0 0 * * ?"

cleanup:
  scheduler:
    cron: "0 0 * * * ?"